// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: fieldstone.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordEvent_Action int32

const (
	RecordEvent_CREATE RecordEvent_Action = 0
	RecordEvent_UPDATE RecordEvent_Action = 1
	RecordEvent_DELETE RecordEvent_Action = 2
)

// Enum value maps for RecordEvent_Action.
var (
	RecordEvent_Action_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
	}
	RecordEvent_Action_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x RecordEvent_Action) Enum() *RecordEvent_Action {
	p := new(RecordEvent_Action)
	*p = x
	return p
}

func (x RecordEvent_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordEvent_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_fieldstone_proto_enumTypes[0].Descriptor()
}

func (RecordEvent_Action) Type() protoreflect.EnumType {
	return &file_fieldstone_proto_enumTypes[0]
}

func (x RecordEvent_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordEvent_Action.Descriptor instead.
func (RecordEvent_Action) EnumDescriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{20, 0}
}

// Health check
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_fieldstone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_fieldstone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Field definition
type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Options       *structpb.Struct       `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_fieldstone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Field) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Field) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

// Collection
type Collection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Fields        []*Field               `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	System        bool                   `protobuf:"varint,5,opt,name=system,proto3" json:"system,omitempty"`
	ListRule      string                 `protobuf:"bytes,6,opt,name=list_rule,json=listRule,proto3" json:"list_rule,omitempty"`
	ViewRule      string                 `protobuf:"bytes,7,opt,name=view_rule,json=viewRule,proto3" json:"view_rule,omitempty"`
	CreateRule    string                 `protobuf:"bytes,8,opt,name=create_rule,json=createRule,proto3" json:"create_rule,omitempty"`
	UpdateRule    string                 `protobuf:"bytes,9,opt,name=update_rule,json=updateRule,proto3" json:"update_rule,omitempty"`
	DeleteRule    string                 `protobuf:"bytes,10,opt,name=delete_rule,json=deleteRule,proto3" json:"delete_rule,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_fieldstone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{3}
}

func (x *Collection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Collection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Collection) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Collection) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Collection) GetSystem() bool {
	if x != nil {
		return x.System
	}
	return false
}

func (x *Collection) GetListRule() string {
	if x != nil {
		return x.ListRule
	}
	return ""
}

func (x *Collection) GetViewRule() string {
	if x != nil {
		return x.ViewRule
	}
	return ""
}

func (x *Collection) GetCreateRule() string {
	if x != nil {
		return x.CreateRule
	}
	return ""
}

func (x *Collection) GetUpdateRule() string {
	if x != nil {
		return x.UpdateRule
	}
	return ""
}

func (x *Collection) GetDeleteRule() string {
	if x != nil {
		return x.DeleteRule
	}
	return ""
}

func (x *Collection) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Collection) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Collection requests/responses
type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_fieldstone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{4}
}

func (x *ListCollectionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListCollectionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCollectionsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Collection          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalItems    int32                  `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_fieldstone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{5}
}

func (x *ListCollectionsResponse) GetItems() []*Collection {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListCollectionsResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *ListCollectionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCollectionsResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListCollectionsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	mi := &file_fieldstone_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{6}
}

func (x *GetCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCollectionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Fields        []*Field               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	System        bool                   `protobuf:"varint,4,opt,name=system,proto3" json:"system,omitempty"`
	ListRule      string                 `protobuf:"bytes,5,opt,name=list_rule,json=listRule,proto3" json:"list_rule,omitempty"`
	ViewRule      string                 `protobuf:"bytes,6,opt,name=view_rule,json=viewRule,proto3" json:"view_rule,omitempty"`
	CreateRule    string                 `protobuf:"bytes,7,opt,name=create_rule,json=createRule,proto3" json:"create_rule,omitempty"`
	UpdateRule    string                 `protobuf:"bytes,8,opt,name=update_rule,json=updateRule,proto3" json:"update_rule,omitempty"`
	DeleteRule    string                 `protobuf:"bytes,9,opt,name=delete_rule,json=deleteRule,proto3" json:"delete_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_fieldstone_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateCollectionRequest) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *CreateCollectionRequest) GetSystem() bool {
	if x != nil {
		return x.System
	}
	return false
}

func (x *CreateCollectionRequest) GetListRule() string {
	if x != nil {
		return x.ListRule
	}
	return ""
}

func (x *CreateCollectionRequest) GetViewRule() string {
	if x != nil {
		return x.ViewRule
	}
	return ""
}

func (x *CreateCollectionRequest) GetCreateRule() string {
	if x != nil {
		return x.CreateRule
	}
	return ""
}

func (x *CreateCollectionRequest) GetUpdateRule() string {
	if x != nil {
		return x.UpdateRule
	}
	return ""
}

func (x *CreateCollectionRequest) GetDeleteRule() string {
	if x != nil {
		return x.DeleteRule
	}
	return ""
}

type UpdateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fields        []*Field               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	ListRule      string                 `protobuf:"bytes,4,opt,name=list_rule,json=listRule,proto3" json:"list_rule,omitempty"`
	ViewRule      string                 `protobuf:"bytes,5,opt,name=view_rule,json=viewRule,proto3" json:"view_rule,omitempty"`
	CreateRule    string                 `protobuf:"bytes,6,opt,name=create_rule,json=createRule,proto3" json:"create_rule,omitempty"`
	UpdateRule    string                 `protobuf:"bytes,7,opt,name=update_rule,json=updateRule,proto3" json:"update_rule,omitempty"`
	DeleteRule    string                 `protobuf:"bytes,8,opt,name=delete_rule,json=deleteRule,proto3" json:"delete_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectionRequest) Reset() {
	*x = UpdateCollectionRequest{}
	mi := &file_fieldstone_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionRequest) ProtoMessage() {}

func (x *UpdateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCollectionRequest) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *UpdateCollectionRequest) GetListRule() string {
	if x != nil {
		return x.ListRule
	}
	return ""
}

func (x *UpdateCollectionRequest) GetViewRule() string {
	if x != nil {
		return x.ViewRule
	}
	return ""
}

func (x *UpdateCollectionRequest) GetCreateRule() string {
	if x != nil {
		return x.CreateRule
	}
	return ""
}

func (x *UpdateCollectionRequest) GetUpdateRule() string {
	if x != nil {
		return x.UpdateRule
	}
	return ""
}

func (x *UpdateCollectionRequest) GetDeleteRule() string {
	if x != nil {
		return x.DeleteRule
	}
	return ""
}

type DeleteCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_fieldstone_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteCollectionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionResponse) Reset() {
	*x = DeleteCollectionResponse{}
	mi := &file_fieldstone_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionResponse) ProtoMessage() {}

func (x *DeleteCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteCollectionResponse) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCollectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Record
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_fieldstone_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{11}
}

func (x *Record) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Record) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *Record) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Record) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Record) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Record) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Record requests/responses
type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  string                 `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,6,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Expand        []string               `protobuf:"bytes,7,rep,name=expand,proto3" json:"expand,omitempty"`
	Fields        []string               `protobuf:"bytes,8,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_fieldstone_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{12}
}

func (x *ListRecordsRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *ListRecordsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListRecordsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListRecordsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListRecordsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRecordsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListRecordsRequest) GetExpand() []string {
	if x != nil {
		return x.Expand
	}
	return nil
}

func (x *ListRecordsRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ListRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Record              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalItems    int32                  `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_fieldstone_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{13}
}

func (x *ListRecordsResponse) GetItems() []*Record {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListRecordsResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *ListRecordsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRecordsResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListRecordsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_fieldstone_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{14}
}

func (x *GetRecordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRecordRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *GetRecordRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CreateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  string                 `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordRequest) Reset() {
	*x = CreateRecordRequest{}
	mi := &file_fieldstone_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordRequest) ProtoMessage() {}

func (x *CreateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateRecordRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{15}
}

func (x *CreateRecordRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *CreateRecordRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateRecordRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecordRequest) Reset() {
	*x = UpdateRecordRequest{}
	mi := &file_fieldstone_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordRequest) ProtoMessage() {}

func (x *UpdateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecordRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateRecordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRecordRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *UpdateRecordRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateRecordRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_fieldstone_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteRecordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRecordRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *DeleteRecordRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordResponse) Reset() {
	*x = DeleteRecordResponse{}
	mi := &file_fieldstone_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordResponse) ProtoMessage() {}

func (x *DeleteRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecordResponse) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Subscription messages
type SubscribeRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  string                 `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRecordsRequest) Reset() {
	*x = SubscribeRecordsRequest{}
	mi := &file_fieldstone_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRecordsRequest) ProtoMessage() {}

func (x *SubscribeRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRecordsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRecordsRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{19}
}

func (x *SubscribeRecordsRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *SubscribeRecordsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SubscribeRecordsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type RecordEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        RecordEvent_Action     `protobuf:"varint,1,opt,name=action,proto3,enum=fieldstone.RecordEvent_Action" json:"action,omitempty"`
	Record        *Record                `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEvent) Reset() {
	*x = RecordEvent{}
	mi := &file_fieldstone_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEvent) ProtoMessage() {}

func (x *RecordEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEvent.ProtoReflect.Descriptor instead.
func (*RecordEvent) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{20}
}

func (x *RecordEvent) GetAction() RecordEvent_Action {
	if x != nil {
		return x.Action
	}
	return RecordEvent_CREATE
}

func (x *RecordEvent) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *RecordEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Auth messages
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_fieldstone_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{21}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegisterRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_fieldstone_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{22}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Record        *User                  `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_fieldstone_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{23}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetRecord() *User {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *AuthResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_fieldstone_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{24}
}

func (x *LogoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_fieldstone_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{25}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_fieldstone_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{26}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type MeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeRequest) Reset() {
	*x = MeRequest{}
	mi := &file_fieldstone_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeRequest) ProtoMessage() {}

func (x *MeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeRequest.ProtoReflect.Descriptor instead.
func (*MeRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{27}
}

// User
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Verified      bool                   `protobuf:"varint,3,opt,name=verified,proto3" json:"verified,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_fieldstone_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{28}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *User) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// General subscription
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"` // "records.create", "users.update", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_fieldstone_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{29}
}

func (x *SubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_fieldstone_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{30}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// File operations
type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadFileRequest_Metadata
	//	*UploadFileRequest_Chunk
	Data          isUploadFileRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_fieldstone_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{31}
}

func (x *UploadFileRequest) GetData() isUploadFileRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadFileRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadFileRequest_Data interface {
	isUploadFileRequest_Data()
}

type UploadFileRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadFileRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadFileRequest_Metadata) isUploadFileRequest_Data() {}

func (*UploadFileRequest_Chunk) isUploadFileRequest_Data() {}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	CollectionId  string                 `protobuf:"bytes,4,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	RecordId      string                 `protobuf:"bytes,5,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_fieldstone_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{32}
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadata) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *FileMetadata) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_fieldstone_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{33}
}

func (x *File) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *File) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *File) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_fieldstone_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{34}
}

func (x *DownloadFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DownloadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_fieldstone_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{35}
}

func (x *DownloadFileResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_fieldstone_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_fieldstone_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fieldstone_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_fieldstone_proto_rawDescGZIP(), []int{37}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_fieldstone_proto protoreflect.FileDescriptor

const file_fieldstone_proto_rawDesc = "" +
	"\n" +
	"\x10fieldstone.proto\x12\n" +
	"fieldstone\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x0f\n" +
	"\rHealthRequest\"|\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"~\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x121\n" +
	"\aoptions\x18\x04 \x01(\v2\x17.google.protobuf.StructR\aoptions\"\xa3\x03\n" +
	"\n" +
	"Collection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12)\n" +
	"\x06fields\x18\x04 \x03(\v2\x11.fieldstone.FieldR\x06fields\x12\x16\n" +
	"\x06system\x18\x05 \x01(\bR\x06system\x12\x1b\n" +
	"\tlist_rule\x18\x06 \x01(\tR\blistRule\x12\x1b\n" +
	"\tview_rule\x18\a \x01(\tR\bviewRule\x12\x1f\n" +
	"\vcreate_rule\x18\b \x01(\tR\n" +
	"createRule\x12\x1f\n" +
	"\vupdate_rule\x18\t \x01(\tR\n" +
	"updateRule\x12\x1f\n" +
	"\vdelete_rule\x18\n" +
	" \x01(\tR\n" +
	"deleteRule\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"d\n" +
	"\x16ListCollectionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"\xb8\x01\n" +
	"\x17ListCollectionsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.fieldstone.CollectionR\x05items\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x05R\n" +
	"totalItems\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"C\n" +
	"\x14GetCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\xaa\x02\n" +
	"\x17CreateCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12)\n" +
	"\x06fields\x18\x03 \x03(\v2\x11.fieldstone.FieldR\x06fields\x12\x16\n" +
	"\x06system\x18\x04 \x01(\bR\x06system\x12\x1b\n" +
	"\tlist_rule\x18\x05 \x01(\tR\blistRule\x12\x1b\n" +
	"\tview_rule\x18\x06 \x01(\tR\bviewRule\x12\x1f\n" +
	"\vcreate_rule\x18\a \x01(\tR\n" +
	"createRule\x12\x1f\n" +
	"\vupdate_rule\x18\b \x01(\tR\n" +
	"updateRule\x12\x1f\n" +
	"\vdelete_rule\x18\t \x01(\tR\n" +
	"deleteRule\"\x85\x02\n" +
	"\x17UpdateCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x06fields\x18\x03 \x03(\v2\x11.fieldstone.FieldR\x06fields\x12\x1b\n" +
	"\tlist_rule\x18\x04 \x01(\tR\blistRule\x12\x1b\n" +
	"\tview_rule\x18\x05 \x01(\tR\bviewRule\x12\x1f\n" +
	"\vcreate_rule\x18\x06 \x01(\tR\n" +
	"createRule\x12\x1f\n" +
	"\vupdate_rule\x18\a \x01(\tR\n" +
	"updateRule\x12\x1f\n" +
	"\vdelete_rule\x18\b \x01(\tR\n" +
	"deleteRule\"F\n" +
	"\x17DeleteCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"4\n" +
	"\x18DeleteCollectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xfd\x01\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe1\x01\n" +
	"\x12ListRecordsRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x06 \x01(\x05R\aperPage\x12\x16\n" +
	"\x06expand\x18\a \x03(\tR\x06expand\x12\x16\n" +
	"\x06fields\x18\b \x03(\tR\x06fields\"\xb0\x01\n" +
	"\x13ListRecordsResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.fieldstone.RecordR\x05items\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x05R\n" +
	"totalItems\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"d\n" +
	"\x10GetRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"\x84\x01\n" +
	"\x13CreateRecordRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\"\x94\x01\n" +
	"\x13UpdateRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\"g\n" +
	"\x13DeleteRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"0\n" +
	"\x14DeleteRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"s\n" +
	"\x17SubscribeRecordsRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"\xd9\x01\n" +
	"\vRecordEvent\x126\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1e.fieldstone.RecordEvent.ActionR\x06action\x12*\n" +
	"\x06record\x18\x02 \x01(\v2\x12.fieldstone.RecordR\x06record\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\",\n" +
	"\x06Action\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\"\x95\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"]\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"\x89\x01\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12(\n" +
	"\x06record\x18\x02 \x01(\v2\x10.fieldstone.UserR\x06record\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"%\n" +
	"\rLogoutRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\v\n" +
	"\tMeRequest\"\xf3\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bverified\x18\x03 \x01(\bR\bverified\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"*\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"\x92\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"k\n" +
	"\x11UploadFileRequest\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.fieldstone.FileMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\xa3\x01\n" +
	"\fFileMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12#\n" +
	"\rcollection_id\x18\x04 \x01(\tR\fcollectionId\x12\x1b\n" +
	"\trecord_id\x18\x05 \x01(\tR\brecordId\"\xb6\x01\n" +
	"\x04File\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"%\n" +
	"\x13DownloadFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x14DownloadFileResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"#\n" +
	"\x11DeleteFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x9a\f\n" +
	"\x11FieldstoneService\x12?\n" +
	"\x06Health\x12\x19.fieldstone.HealthRequest\x1a\x1a.fieldstone.HealthResponse\x12Z\n" +
	"\x0fListCollections\x12\".fieldstone.ListCollectionsRequest\x1a#.fieldstone.ListCollectionsResponse\x12I\n" +
	"\rGetCollection\x12 .fieldstone.GetCollectionRequest\x1a\x16.fieldstone.Collection\x12O\n" +
	"\x10CreateCollection\x12#.fieldstone.CreateCollectionRequest\x1a\x16.fieldstone.Collection\x12O\n" +
	"\x10UpdateCollection\x12#.fieldstone.UpdateCollectionRequest\x1a\x16.fieldstone.Collection\x12]\n" +
	"\x10DeleteCollection\x12#.fieldstone.DeleteCollectionRequest\x1a$.fieldstone.DeleteCollectionResponse\x12N\n" +
	"\vListRecords\x12\x1e.fieldstone.ListRecordsRequest\x1a\x1f.fieldstone.ListRecordsResponse\x12=\n" +
	"\tGetRecord\x12\x1c.fieldstone.GetRecordRequest\x1a\x12.fieldstone.Record\x12C\n" +
	"\fCreateRecord\x12\x1f.fieldstone.CreateRecordRequest\x1a\x12.fieldstone.Record\x12C\n" +
	"\fUpdateRecord\x12\x1f.fieldstone.UpdateRecordRequest\x1a\x12.fieldstone.Record\x12Q\n" +
	"\fDeleteRecord\x12\x1f.fieldstone.DeleteRecordRequest\x1a .fieldstone.DeleteRecordResponse\x12R\n" +
	"\x10SubscribeRecords\x12#.fieldstone.SubscribeRecordsRequest\x1a\x17.fieldstone.RecordEvent0\x01\x12A\n" +
	"\bRegister\x12\x1b.fieldstone.RegisterRequest\x1a\x18.fieldstone.AuthResponse\x12;\n" +
	"\x05Login\x12\x18.fieldstone.LoginRequest\x1a\x18.fieldstone.AuthResponse\x12?\n" +
	"\x06Logout\x12\x19.fieldstone.LogoutRequest\x1a\x1a.fieldstone.LogoutResponse\x12I\n" +
	"\fRefreshToken\x12\x1f.fieldstone.RefreshTokenRequest\x1a\x18.fieldstone.AuthResponse\x12-\n" +
	"\x02Me\x12\x15.fieldstone.MeRequest\x1a\x10.fieldstone.User\x12>\n" +
	"\tSubscribe\x12\x1c.fieldstone.SubscribeRequest\x1a\x11.fieldstone.Event0\x01\x12?\n" +
	"\n" +
	"UploadFile\x12\x1d.fieldstone.UploadFileRequest\x1a\x10.fieldstone.File(\x01\x12S\n" +
	"\fDownloadFile\x12\x1f.fieldstone.DownloadFileRequest\x1a .fieldstone.DownloadFileResponse0\x01\x12K\n" +
	"\n" +
	"DeleteFile\x12\x1d.fieldstone.DeleteFileRequest\x1a\x1e.fieldstone.DeleteFileResponseB2Z0github.com/fieldstone/fieldstone/api/proto;protob\x06proto3"

var (
	file_fieldstone_proto_rawDescOnce sync.Once
	file_fieldstone_proto_rawDescData []byte
)

func file_fieldstone_proto_rawDescGZIP() []byte {
	file_fieldstone_proto_rawDescOnce.Do(func() {
		file_fieldstone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fieldstone_proto_rawDesc), len(file_fieldstone_proto_rawDesc)))
	})
	return file_fieldstone_proto_rawDescData
}

var file_fieldstone_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fieldstone_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_fieldstone_proto_goTypes = []any{
	(RecordEvent_Action)(0),          // 0: fieldstone.RecordEvent.Action
	(*HealthRequest)(nil),            // 1: fieldstone.HealthRequest
	(*HealthResponse)(nil),           // 2: fieldstone.HealthResponse
	(*Field)(nil),                    // 3: fieldstone.Field
	(*Collection)(nil),               // 4: fieldstone.Collection
	(*ListCollectionsRequest)(nil),   // 5: fieldstone.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),  // 6: fieldstone.ListCollectionsResponse
	(*GetCollectionRequest)(nil),     // 7: fieldstone.GetCollectionRequest
	(*CreateCollectionRequest)(nil),  // 8: fieldstone.CreateCollectionRequest
	(*UpdateCollectionRequest)(nil),  // 9: fieldstone.UpdateCollectionRequest
	(*DeleteCollectionRequest)(nil),  // 10: fieldstone.DeleteCollectionRequest
	(*DeleteCollectionResponse)(nil), // 11: fieldstone.DeleteCollectionResponse
	(*Record)(nil),                   // 12: fieldstone.Record
	(*ListRecordsRequest)(nil),       // 13: fieldstone.ListRecordsRequest
	(*ListRecordsResponse)(nil),      // 14: fieldstone.ListRecordsResponse
	(*GetRecordRequest)(nil),         // 15: fieldstone.GetRecordRequest
	(*CreateRecordRequest)(nil),      // 16: fieldstone.CreateRecordRequest
	(*UpdateRecordRequest)(nil),      // 17: fieldstone.UpdateRecordRequest
	(*DeleteRecordRequest)(nil),      // 18: fieldstone.DeleteRecordRequest
	(*DeleteRecordResponse)(nil),     // 19: fieldstone.DeleteRecordResponse
	(*SubscribeRecordsRequest)(nil),  // 20: fieldstone.SubscribeRecordsRequest
	(*RecordEvent)(nil),              // 21: fieldstone.RecordEvent
	(*RegisterRequest)(nil),          // 22: fieldstone.RegisterRequest
	(*LoginRequest)(nil),             // 23: fieldstone.LoginRequest
	(*AuthResponse)(nil),             // 24: fieldstone.AuthResponse
	(*LogoutRequest)(nil),            // 25: fieldstone.LogoutRequest
	(*LogoutResponse)(nil),           // 26: fieldstone.LogoutResponse
	(*RefreshTokenRequest)(nil),      // 27: fieldstone.RefreshTokenRequest
	(*MeRequest)(nil),                // 28: fieldstone.MeRequest
	(*User)(nil),                     // 29: fieldstone.User
	(*SubscribeRequest)(nil),         // 30: fieldstone.SubscribeRequest
	(*Event)(nil),                    // 31: fieldstone.Event
	(*UploadFileRequest)(nil),        // 32: fieldstone.UploadFileRequest
	(*FileMetadata)(nil),             // 33: fieldstone.FileMetadata
	(*File)(nil),                     // 34: fieldstone.File
	(*DownloadFileRequest)(nil),      // 35: fieldstone.DownloadFileRequest
	(*DownloadFileResponse)(nil),     // 36: fieldstone.DownloadFileResponse
	(*DeleteFileRequest)(nil),        // 37: fieldstone.DeleteFileRequest
	(*DeleteFileResponse)(nil),       // 38: fieldstone.DeleteFileResponse
	(*timestamppb.Timestamp)(nil),    // 39: google.protobuf.Timestamp
	(*structpb.Struct)(nil),          // 40: google.protobuf.Struct
}
var file_fieldstone_proto_depIdxs = []int32{
	39, // 0: fieldstone.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	40, // 1: fieldstone.Field.options:type_name -> google.protobuf.Struct
	3,  // 2: fieldstone.Collection.fields:type_name -> fieldstone.Field
	39, // 3: fieldstone.Collection.created_at:type_name -> google.protobuf.Timestamp
	39, // 4: fieldstone.Collection.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 5: fieldstone.ListCollectionsResponse.items:type_name -> fieldstone.Collection
	3,  // 6: fieldstone.CreateCollectionRequest.fields:type_name -> fieldstone.Field
	3,  // 7: fieldstone.UpdateCollectionRequest.fields:type_name -> fieldstone.Field
	40, // 8: fieldstone.Record.data:type_name -> google.protobuf.Struct
	39, // 9: fieldstone.Record.created_at:type_name -> google.protobuf.Timestamp
	39, // 10: fieldstone.Record.updated_at:type_name -> google.protobuf.Timestamp
	12, // 11: fieldstone.ListRecordsResponse.items:type_name -> fieldstone.Record
	40, // 12: fieldstone.CreateRecordRequest.data:type_name -> google.protobuf.Struct
	40, // 13: fieldstone.UpdateRecordRequest.data:type_name -> google.protobuf.Struct
	0,  // 14: fieldstone.RecordEvent.action:type_name -> fieldstone.RecordEvent.Action
	12, // 15: fieldstone.RecordEvent.record:type_name -> fieldstone.Record
	39, // 16: fieldstone.RecordEvent.timestamp:type_name -> google.protobuf.Timestamp
	40, // 17: fieldstone.RegisterRequest.metadata:type_name -> google.protobuf.Struct
	29, // 18: fieldstone.AuthResponse.record:type_name -> fieldstone.User
	39, // 19: fieldstone.AuthResponse.expires_at:type_name -> google.protobuf.Timestamp
	40, // 20: fieldstone.User.metadata:type_name -> google.protobuf.Struct
	39, // 21: fieldstone.User.created_at:type_name -> google.protobuf.Timestamp
	39, // 22: fieldstone.User.updated_at:type_name -> google.protobuf.Timestamp
	40, // 23: fieldstone.Event.data:type_name -> google.protobuf.Struct
	39, // 24: fieldstone.Event.timestamp:type_name -> google.protobuf.Timestamp
	33, // 25: fieldstone.UploadFileRequest.metadata:type_name -> fieldstone.FileMetadata
	39, // 26: fieldstone.File.created_at:type_name -> google.protobuf.Timestamp
	1,  // 27: fieldstone.FieldstoneService.Health:input_type -> fieldstone.HealthRequest
	5,  // 28: fieldstone.FieldstoneService.ListCollections:input_type -> fieldstone.ListCollectionsRequest
	7,  // 29: fieldstone.FieldstoneService.GetCollection:input_type -> fieldstone.GetCollectionRequest
	8,  // 30: fieldstone.FieldstoneService.CreateCollection:input_type -> fieldstone.CreateCollectionRequest
	9,  // 31: fieldstone.FieldstoneService.UpdateCollection:input_type -> fieldstone.UpdateCollectionRequest
	10, // 32: fieldstone.FieldstoneService.DeleteCollection:input_type -> fieldstone.DeleteCollectionRequest
	13, // 33: fieldstone.FieldstoneService.ListRecords:input_type -> fieldstone.ListRecordsRequest
	15, // 34: fieldstone.FieldstoneService.GetRecord:input_type -> fieldstone.GetRecordRequest
	16, // 35: fieldstone.FieldstoneService.CreateRecord:input_type -> fieldstone.CreateRecordRequest
	17, // 36: fieldstone.FieldstoneService.UpdateRecord:input_type -> fieldstone.UpdateRecordRequest
	18, // 37: fieldstone.FieldstoneService.DeleteRecord:input_type -> fieldstone.DeleteRecordRequest
	20, // 38: fieldstone.FieldstoneService.SubscribeRecords:input_type -> fieldstone.SubscribeRecordsRequest
	22, // 39: fieldstone.FieldstoneService.Register:input_type -> fieldstone.RegisterRequest
	23, // 40: fieldstone.FieldstoneService.Login:input_type -> fieldstone.LoginRequest
	25, // 41: fieldstone.FieldstoneService.Logout:input_type -> fieldstone.LogoutRequest
	27, // 42: fieldstone.FieldstoneService.RefreshToken:input_type -> fieldstone.RefreshTokenRequest
	28, // 43: fieldstone.FieldstoneService.Me:input_type -> fieldstone.MeRequest
	30, // 44: fieldstone.FieldstoneService.Subscribe:input_type -> fieldstone.SubscribeRequest
	32, // 45: fieldstone.FieldstoneService.UploadFile:input_type -> fieldstone.UploadFileRequest
	35, // 46: fieldstone.FieldstoneService.DownloadFile:input_type -> fieldstone.DownloadFileRequest
	37, // 47: fieldstone.FieldstoneService.DeleteFile:input_type -> fieldstone.DeleteFileRequest
	2,  // 48: fieldstone.FieldstoneService.Health:output_type -> fieldstone.HealthResponse
	6,  // 49: fieldstone.FieldstoneService.ListCollections:output_type -> fieldstone.ListCollectionsResponse
	4,  // 50: fieldstone.FieldstoneService.GetCollection:output_type -> fieldstone.Collection
	4,  // 51: fieldstone.FieldstoneService.CreateCollection:output_type -> fieldstone.Collection
	4,  // 52: fieldstone.FieldstoneService.UpdateCollection:output_type -> fieldstone.Collection
	11, // 53: fieldstone.FieldstoneService.DeleteCollection:output_type -> fieldstone.DeleteCollectionResponse
	14, // 54: fieldstone.FieldstoneService.ListRecords:output_type -> fieldstone.ListRecordsResponse
	12, // 55: fieldstone.FieldstoneService.GetRecord:output_type -> fieldstone.Record
	12, // 56: fieldstone.FieldstoneService.CreateRecord:output_type -> fieldstone.Record
	12, // 57: fieldstone.FieldstoneService.UpdateRecord:output_type -> fieldstone.Record
	19, // 58: fieldstone.FieldstoneService.DeleteRecord:output_type -> fieldstone.DeleteRecordResponse
	21, // 59: fieldstone.FieldstoneService.SubscribeRecords:output_type -> fieldstone.RecordEvent
	24, // 60: fieldstone.FieldstoneService.Register:output_type -> fieldstone.AuthResponse
	24, // 61: fieldstone.FieldstoneService.Login:output_type -> fieldstone.AuthResponse
	26, // 62: fieldstone.FieldstoneService.Logout:output_type -> fieldstone.LogoutResponse
	24, // 63: fieldstone.FieldstoneService.RefreshToken:output_type -> fieldstone.AuthResponse
	29, // 64: fieldstone.FieldstoneService.Me:output_type -> fieldstone.User
	31, // 65: fieldstone.FieldstoneService.Subscribe:output_type -> fieldstone.Event
	34, // 66: fieldstone.FieldstoneService.UploadFile:output_type -> fieldstone.File
	36, // 67: fieldstone.FieldstoneService.DownloadFile:output_type -> fieldstone.DownloadFileResponse
	38, // 68: fieldstone.FieldstoneService.DeleteFile:output_type -> fieldstone.DeleteFileResponse
	48, // [48:69] is the sub-list for method output_type
	27, // [27:48] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_fieldstone_proto_init() }
func file_fieldstone_proto_init() {
	if File_fieldstone_proto != nil {
		return
	}
	file_fieldstone_proto_msgTypes[31].OneofWrappers = []any{
		(*UploadFileRequest_Metadata)(nil),
		(*UploadFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fieldstone_proto_rawDesc), len(file_fieldstone_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fieldstone_proto_goTypes,
		DependencyIndexes: file_fieldstone_proto_depIdxs,
		EnumInfos:         file_fieldstone_proto_enumTypes,
		MessageInfos:      file_fieldstone_proto_msgTypes,
	}.Build()
	File_fieldstone_proto = out.File
	file_fieldstone_proto_goTypes = nil
	file_fieldstone_proto_depIdxs = nil
}
